# Generated by Django 3.0.6 on 2020-05-31 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200530_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hidden_loc',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=500),
        ),
    ]
