# Generated by Django 3.0.6 on 2020-06-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200531_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trust',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
