# Generated by Django 3.0.6 on 2020-06-02 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_profile_trust'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='money',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='baedal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='최대 100자 내로 입력가능합니다.', max_length=100)),
                ('deadline', models.CharField(max_length=20)),
                ('applink', models.CharField(max_length=100)),
                ('lowerlimit', models.CharField(max_length=100)),
                ('baedal_tip', models.CharField(max_length=100)),
                ('openkakaolink', models.CharField(max_length=100)),
                ('memo', models.TextField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baedal_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
