# Generated by Django 3.0.6 on 2020-06-02 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200602_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='최대 100자 내로 입력가능합니다.', max_length=100)),
                ('deadline1', models.CharField(max_length=20)),
                ('deadline2', models.CharField(max_length=20)),
                ('appLink', models.CharField(max_length=100)),
                ('left', models.CharField(max_length=100)),
                ('baedalTip', models.CharField(max_length=100)),
                ('kakaolLnk', models.CharField(max_length=100)),
                ('memo', models.TextField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_id', to='app.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='franchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='최대 100자 내로 입력가능합니다.', max_length=100)),
                ('deadline1', models.CharField(max_length=20)),
                ('deadline2', models.CharField(max_length=20)),
                ('shop', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=50)),
                ('kakaolLnk', models.CharField(max_length=100)),
                ('memo', models.TextField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='franchise_id', to='app.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='최대 100자 내로 입력가능합니다.', max_length=100)),
                ('deadline1', models.CharField(max_length=20)),
                ('deadline2', models.CharField(max_length=20)),
                ('siteLink', models.CharField(max_length=100)),
                ('kakaolLnk', models.CharField(max_length=100)),
                ('memo', models.TextField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='others_id', to='app.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='OTT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='최대 100자 내로 입력가능합니다.', max_length=100)),
                ('people', models.CharField(max_length=10)),
                ('appLink', models.CharField(max_length=100)),
                ('memo', models.TextField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OTT_id', to='app.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='최대 100자 내로 입력가능합니다.', max_length=100)),
                ('deadline1', models.CharField(max_length=20)),
                ('deadline2', models.CharField(max_length=20)),
                ('siteLink', models.CharField(max_length=100)),
                ('left', models.CharField(max_length=100)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_id', to='app.Profile')),
            ],
        ),
        migrations.DeleteModel(
            name='baedal',
        ),
    ]
