# Generated by Django 3.0.6 on 2020-06-02 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200602_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ott',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ott_id', to='app.Profile'),
        ),
    ]
