# Generated by Django 3.0.6 on 2020-06-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200602_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='end',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='end',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='others',
            name='end',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ott',
            name='end',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shopping',
            name='end',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
