# Generated by Django 3.0.6 on 2020-06-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200602_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='others',
            old_name='kakaolLnk',
            new_name='kakaolLink',
        ),
        migrations.AddField(
            model_name='food',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
