# Generated by Django 3.0.6 on 2020-06-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200602_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='deadline1',
            field=models.TextField(max_length=20),
        ),
    ]
