# Generated by Django 3.0.6 on 2020-06-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200606_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.TextField(null=True),
        ),
    ]
