# Generated by Django 3.0.6 on 2020-06-06 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='kakaolLnk',
            new_name='kakaoLink',
        ),
    ]
