# Generated by Django 3.0.6 on 2020-06-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200606_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='memo',
            field=models.TextField(null=True),
        ),
    ]
