# Generated by Django 3.0.6 on 2020-06-06 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_shopping_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='franchise_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='others',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='others_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ott',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ott_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
