# Generated by Django 3.0.6 on 2020-06-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200606_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='ott',
            name='service',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
