# Generated by Django 3.0.6 on 2020-06-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_ott_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='shop',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
