# Generated by Django 3.0.6 on 2020-06-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_food_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='savemoney',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
