# Generated by Django 3.0.6 on 2020-06-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_food_savemoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='author_location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
