# Generated by Django 3.0.6 on 2020-06-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_food_author_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='author_location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shopping',
            name='author_location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
