# Generated by Django 3.0.6 on 2020-06-06 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200606_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='franchise',
            old_name='author_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='shopping',
            old_name='author_location',
            new_name='location',
        ),
    ]
